[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "networkD"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pandas>1,<3",
    "numpy>=1,<3",
]

# tools
[tool.black]
line-length = 88
target-version = ["py310", "py311", "py312"]